### PR TITLE
Update Plugin for Logic 2

### PR DESCRIPTION
**Pull request by mbrunnen**
Streamlined the plugin to the official [Sample Plugin](https://github.com/saleae/SampleAnalyzer).

Tested on Logic version v2.4.6.

### CODE REVIEW

**Comment by ewfuentes** [comment]
Thank you for the contribution! I tried to build and I got the following output:
```
~/code/SaleaeSDIOAnalyzer(master ?:1 ✗) cmake -H. -Bbuild -DCMAKE_INSTALL_PREFIX=$HOME/.local/share/saleae -GNinja
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:4 (message):
  CMake support is still experimental!


CMake Error at CMakeLists.txt:25 (message):
  Analyzer SDK include directory not found


-- 64 Bit detected
CMake Error at CMakeLists.txt:66 (message):
  Analyzer SDK library not found
  ```

I'm not super familiar with cmake, but a cursory look at the change leads me to believe that it should fetch the sdk repo automatically. Is that correct?

**Comment by mbrunnen** [comment]
> I'm not super familiar with cmake, but a cursory look at the change leads me to believe that it should fetch the sdk repo automatically. Is that correct?
Yes, this is correct.

Theses messages seem to be from the master branch, not from my PR. Could you please make sure, that you have 7461d614b27b3afdab002901a401280199206233 checked and test again? :)

**Comment by mbrunnen** [comment]
I hope @kuym is ok, with taking his CRC feature. I added you to the license declaration and marked you as author in the commit message.

**Comment by ewfuentes** [comment]
> That is correct. These messages, though, seem to be from the master branch, not from my PR. Could you please make sure, that you have https://github.com/ewfuentes/SaleaeSDIOAnalyzer/commit/7461d614b27b3afdab002901a401280199206233 checked out and test again? :)

 Ahh yes, I missed that you are merging from main. This PR looks reasonable to me. I'll add you as a collaborator and feel free to merge when you're ready.

**Pull request merged**
